<?php if(!defined('PLX_ROOT')) exit; 
  # get template path
  ob_start();
  $plxShow->template();
  $templatepath = ob_get_clean();
?>

<section class="comments col sml-12 sml-centered" >

  <?php if($plxShow->plxMotor->plxRecord_coms): ?>


  <h2>
    <a href="#" id="comments"></a><?php echo $plxShow->artNbCom(); ?>
  </h2>


  <?php while($plxShow->plxMotor->plxRecord_coms->loop()): # Loop on building comments ?>
  <?php 
    # get author name as a seed
    $seed = $plxShow->plxMotor->plxRecord_coms->f('author'); 
    $seed = preg_replace('/[^A-Za-z0-9\._-]/', '', $seed); 
    $seed = substr($seed,0,35).''; 
    
    $avatarpath = ''.$templatepath.'/cat-avatar-generator.php?seed='.$seed.'';
    
    # Build exeption, register members:
    # Deevad
    if($plxShow->plxMotor->plxRecord_coms->f('type')=='admin' OR $seed=="DavidRevoy" OR $seed=="Deevad" OR $seed=="deevad" ) {
    $avatarpath = ''.$templatepath.'/avatars/static_avatar_carrot.png';
    $userstatus = 'Author';
    $permission = 'admin';
    
    # Craig Maloney
    } elseif ($seed=="cmaloney" OR $seed=="CraigMaloney") {
    $avatarpath = ''.$templatepath.'/avatars/static_avatar_cmaloney.png';
    $userstatus = 'Contributor';
    $permission = 'admin';
    
    # Valvin
    } elseif ($seed=="valvin" OR $seed=="Valvin") {
    $userstatus = 'Contributor';
    $permission = 'admin';
    
    # Nartance
    } elseif ($seed=="nartance" OR $seed=="Nartance") {
    $userstatus = 'Contributor';
    $permission = 'admin';
    
    # Midgard
    } elseif ($seed=="Midgard") {
    $permission = 'admin';
    $userstatus = 'Contributor';
    $avatarpath = ''.$templatepath.'/avatars/static_avatar_midgard.png';
    
    # Nartance
    } elseif ($seed=="CGand" OR $seed=="cgand" OR $seed=="Cgand" ) {
    $userstatus = 'Translator';
    $permission = 'admin';
    
    # Misty Tales: http://www.peppercarrot.com/en/article391/cat-avatar-generator#c0391-722
    } elseif ($seed=="MistyTales") {
    $seed = '583f7b02633e4';
    $permission = 'normal';
    $userstatus = '';
    $avatarpath = ''.$templatepath.'/cat-avatar-generator.php?seed='.$seed.'';
    
    } else {
    $userstatus = '';
    $permission = 'normal';
    }
  ?>
    <div id="<?php $plxShow->comId(); ?>" class="singlecom <?php echo $permission ?> <?php $plxShow->comLevel(); ?> grid">
      <div id="com-<?php $plxShow->comIndex(); ?>">
        
        <div class="avatar col sml-2 med-2 lrg-2">
          <p>
            <a href="http://www.peppercarrot.com/extras/html/2016_cat-generator/index.php?seed=<?php echo $seed; ?>" >
              <img height="70px" width="70px" src="<?php echo $avatarpath; ?>" alt="<?php echo $seed; ?>'s avatar" title="<?php echo $seed; ?>'s autogenerated avatar, made with the Cat Avatar Generator! click to visit" />
            </a>
          </p>
        </div>

        <div class="col sml-10 med-10 lrg-10"><p>
          <a href="<?php $plxShow->ComUrl(); ?>" title="#<?php echo $plxShow->plxMotor->plxRecord_coms->i+1 ?>">
            <img class="svg" src="themes/peppercarrot-theme_v2/ico/link.svg" alt="link"/>
          </a>&nbsp;
          <strong>
            <?php $plxShow->comAuthor('link'); ?>
          </strong>&nbsp;
          <small>
            <?php if($userstatus): ?>
                    <span style="color: #85BF25;">
                      <?php echo $userstatus; ?>,
                    </span>
            <?php else: ?>
                    &nbsp;
            <?php endif; ?>

            <time datetime="<?php $plxShow->comDate('#num_year(4)-#num_month-#num_day #hour:#minute'); ?>">
            <?php $plxShow->comDate('#num_day #month #num_year(4), #hour:#minute'); ?></time> -

            <?php if($plxShow->plxMotor->plxRecord_arts->f('allow_com') AND $plxShow->plxMotor->aConf['allow_com']): ?>
                    <a rel="nofollow" href="<?php $plxShow->artUrl(); ?>#form" onclick="replyCom('<?php $plxShow->comIndex() ?>')">Reply</a>
            <?php endif; ?>
          </small>
          <p class="com_content type-<?php $plxShow->comType(); ?>">
            <?php $plxShow->comContent(); ?>
          </p>
        </div>
        
      </div>
  </div>

  <?php endwhile; # End loop ?>



    <?php endif; ?>

    <?php if($plxShow->plxMotor->plxRecord_arts->f('allow_com') AND $plxShow->plxMotor->aConf['allow_com']): ?>

    <h2>Leave a reply</h2>

	<form id="form" action="<?php $plxShow->artUrl(); ?>#form" method="post">

		<fieldset>

			<div class="grid">
				<div class="col sml-12">
					<label for="id_name">Name:</label>
					<input id="id_name" name="name" type="text" size="20" value="<?php $plxShow->comGet('name',''); ?>" maxlength="30" />
				</div>
			</div>
			<div class="grid">
				<div class="col sml-12 lrg-6">
					<label for="id_mail">Email (optional):</label>
					<input id="id_mail" name="mail" type="text" size="20" value="<?php $plxShow->comGet('mail',''); ?>" />
				</div>
				<div class="col sml-12 lrg-6">
					<label for="id_site">Website (optional):</label>
					<input id="id_site" name="site" type="text" size="20" value="<?php $plxShow->comGet('site',''); ?>" />
				</div>
			</div>
			<div class="grid">
				<div class="col sml-12">
          <div id="id_answer"></div>
					<label for="id_content" class="lab_com">Your comment: </label>
					<textarea id="id_content" name="content" cols="35" rows="6"><?php $plxShow->comGet('content',''); ?></textarea>
				</div>
				<p style="color:#CCC; margin: 0 0 1rem 0;">Notice: URLs allowed (auto-clickable). URLs to pictures too (gif, jpg, png; auto-displayed)</p>
			</div>

			<?php $plxShow->comMessage('<p class="text-red"><strong>#com_message</strong></p>'); ?>

			<?php if($plxShow->plxMotor->aConf['capcha']): ?>

		<div class="grid">
			<div class="col sml-12">
				<label for="id_rep"><strong>Antispam capcha</strong></label>
				<?php $plxShow->capchaQ(); ?>
				<input id="id_rep" name="rep" type="text" size="2" maxlength="1" style="width: auto; display: inline;" />
			</div>
		</div>
  <?php endif; ?>

			<div class="grid">
				<div class="col sml-12">
          <input type="hidden" id="id_parent" name="parent" value="<?php $plxShow->comGet('parent',''); ?>" />
          <input class="blue" type="submit" value="Post your comment" />
				</div>
			</div>

		</fieldset>

	</form>

    <script>
    function replyCom(idCom) {
      document.getElementById('id_answer').innerHTML='Reply to:';
      document.getElementById('id_answer').innerHTML+=document.getElementById('com-'+idCom).innerHTML;
      document.getElementById('id_answer').innerHTML+='<a rel="nofollow" href="<?php $plxShow->artUrl(); ?>#form" onclick="cancelCom()"> (cancel)</a>';
      document.getElementById('id_answer').style.display='inline-block';
      document.getElementById('id_parent').value=idCom;
      document.getElementById('id_content').focus();
    }
    function cancelCom() {
      document.getElementById('id_answer').style.display='none';
      document.getElementById('id_parent').value='';
      document.getElementById('com_message').innerHTML='';
    }
    var parent = document.getElementById('id_parent').value;
    if(parent!='') { replyCom(parent) }
    </script>

    <?php else: ?>

    <p>
      <h4> Comments are closed for this article</h4>.
    </p>

    <?php endif; # Fin du if sur l'autorisation des commentaires ?>
    
</section>
